stages:
  gazetteer:
    cmd: python -m scripts.preprocessing.gazetteer
    deps:
    - scripts/preprocessing/gazetteer.py

    - ${DATA_DIR}/lad-2021.gpkg
    - ${DATA_DIR}/gbpn-2021_14_06.csv
    - ${DATA_DIR}/os_opname-2023_02_21
    outs:
      - data/processed/gazetteer.parquet
    frozen: false
  combine_comments:
    cmd: python -m scripts.preprocessing.combine_comments
    deps:
      - scripts/preprocessing/combine_comments.py

      - ${DATA_DIR}/comments-2022_04_17
    outs:
      - data/processed/comments.parquet
    frozen: false
  ner:
    cmd: python -m scripts.preprocessing.ner
    deps:
      - scripts/preprocessing/ner.py

      - data/processed/comments.parquet
    outs:
      - data/processed/ner.csv:
          push: false
    frozen: true
  geocode:
    cmd: python -m scripts.preprocessing.geocode
    deps:
      - scripts/preprocessing/geocode.py

      - data/processed/ner.csv
      - data/processed/gazetteer.parquet
      - ${DATA_DIR}/subreddits-2023_02_21.parquet
    outs:
      - data/processed/geocoded.csv:
          push: false
    frozen: true
  association:
    cmd: python -m scripts.analysis.process
    deps:
      - scripts/analysis/process.py
      - scripts/analysis/pci.py

      - data/processed/geocoded.csv
      - data/processed/gazetteer.parquet
    outs:
      - data/out/places_full.parquet
      - data/out/places.parquet
      - data/out/pci_h3.parquet
    frozen: false
  regressions:
    cmd: python -m scripts.analysis.regressions
    deps:
      - scripts/analysis/regressions.py

      - data/out/pci_h3.parquet
    outs:
      - data/out/regressions/lr_metrics.json
      - data/out/regressions/lr.parquet
      - data/out/regressions/mm.parquet
      - data/out/regressions/mm_random_effects.parquet
      - data/out/regressions/mm_metrics.json
    frozen: false
  h3_poly:
    cmd: python -m scripts.preprocessing.h3_poly
    deps:
      - scripts/preprocessing/h3_poly.py

      - data/out/places.parquet
